[package]
name = "rocket"
version = "1.0.0"
authors = ["Adolfo Ochagavía <aochagavia92@gmail.com>"]
build = "build.rs"

[dependencies]

itertools-num = "~0.1"
rand = "~0.6"
ggez = "~0.4"
structopt = "~0.2"

[features]
default = []
debug = []
